#!/usr/bin/env bash
# RUN -- launch the Tugbot simulation via the P4 distributed launcher
#
# P4 reads session.pro which starts two processes:
#   Proc 1: Ada tugbot_main  (PACE web server + simulation tasks)
#   Proc 2: gz sim -r tugbot.sdf  (Gazebo 3D visualiser)
#
# After launch the PACE web server is available for remote manipulation:
#
#   Navigate forward at 80% speed:
#     curl "http://localhost:8080/Tugbot.Navigate_Action?set=<xml><direction>forward</direction><speed>0.8</speed></xml>"
#
#   Turn left:
#     curl "http://localhost:8080/Tugbot.Navigate_Action?set=<xml><direction>left</direction><speed>0.5</speed></xml>"
#
#   Stop:
#     curl "http://localhost:8080/Tugbot.Navigate_Action?set=<xml><direction>stop</direction></xml>"
#
#   Open/close gripper:
#     curl "http://localhost:8080/Tugbot.Gripper_Action?set=<xml><state>close</state></xml>"
#     curl "http://localhost:8080/Tugbot.Gripper_Action?set=<xml><state>open</state></xml>"
#
#   Enable/disable warning beacon:
#     curl "http://localhost:8080/Tugbot.Light_Action?set=<xml><enabled>true</enabled></xml>"
#
#   Query status:
#     curl "http://localhost:8080/Tugbot.Status_Action"

env P4PATH="../../launch.pro" ../../drivers/p4
