with Pace.Log;
with Producer_Pkg;
with Processor_Pkg;
--with Consumer_Pkg;
with Ada.Text_IO;

procedure Sim_Main is
begin
   Pace.Log.Agent_Id;
   Ada.Text_IO.Put_Line ("Discrete Event Simulation Started (Node 0).");
   
   -- In simulation mode (PACE_SIM=1), this will jump through time
   -- based on the events generated by the tasks.
   Pace.Log.Wait (100.0); 
   
   Ada.Text_IO.Put_Line ("Simulation Time limit reached. Exiting.");
   Pace.Log.Os_Exit (0);
end Sim_Main;
