package Pace.Ports is
   -----------------------------------------
   -- PORTS -- Generates Socket port numbers
   -----------------------------------------
   pragma Elaborate_Body;

   type Services is (Messaging, Web, Other);
   -- Messaging ports are defined via configuration file or are enumerated

   --
   -- Host_And_Port name is constructed by adding Node Num to Base Port
   --  OR it is generated by the name server if it exists
   --
   --   example -- bigbird:5500+1 = bigbird:5501
   --
   function Unique_Name (Service : Services) return String;
   function Unique_Port (Service : Services; -- if node given find port
                         Node : Integer) return Integer;
   function Unique_Port (Service : Services; -- string version
                         Node : Integer) return String;

   --
   -- Name server interface for messaging service, provides unique address name
   --
   function Get_Address_From_Name_Server (Node : in Integer) return String;
   procedure Set_Address_To_Name_Server (Node : in Integer);

   -- Name server keys
   function Put_Msg_Port return String;
   function Get_Msg_Port return String;
   function Put_Web_Port return String;
   function Get_Web_Port return String;

   ------------------------------------------------------------------------------
   -- $id: pace-ports.ads,v 1.1 09/16/2002 18:18:33 pukitepa Exp $
   ------------------------------------------------------------------------------
end Pace.Ports;
