--  Abstract :
--
--  Text_IO for types in SAL.Gen_Math.Gen_DOF_3
--
--  This file is auto-generated by auto_text_io
--  from SAL.Gen_Math.Gen_DOF_3
--
with Boolean_Text_IO;                     use Boolean_Text_IO;
with Sal.Gen_Array_Text_Io;
with Sal.Gen_Math.Gen_Scalar.Gen_Text_Io;
with Sal.Gen_Math.Gen_Text_Io;
with Ada.Text_IO;
generic
   with package Math_Text_Io is new Sal.Gen_Math.Gen_Text_Io;
   with package Math_Scalar_Text_Io is new Parent_Math_Scalar.Gen_Text_Io (
      Math_Text_Io);
package Sal.Gen_Math.Gen_Dof_3.Gen_Text_Io is
   pragma Elaborate_Body;

   package Cart_Axis_Text_Io is new Ada.Text_IO.Enumeration_IO (
      Cart_Axis_Type);
   procedure Put
     (File  : in Ada.Text_IO.File_Type;
      Item  : in Cart_Axis_Type;
      Width : in Ada.Text_IO.Field    := Cart_Axis_Text_Io.Default_Width;
      Set   : in Ada.Text_IO.Type_Set := Cart_Axis_Text_Io.Default_Setting) 
renames Cart_Axis_Text_Io.Put;
   procedure Get
     (File : in Ada.Text_IO.File_Type;
      Item : out Cart_Axis_Type) renames Cart_Axis_Text_Io.Get;
   procedure Put
     (Item  : in Cart_Axis_Type;
      Width : in Ada.Text_IO.Field    := Cart_Axis_Text_Io.Default_Width;
      Set   : in Ada.Text_IO.Type_Set := Cart_Axis_Text_Io.Default_Setting) 
renames Cart_Axis_Text_Io.Put;
   procedure Get (Item : out Cart_Axis_Type) renames Cart_Axis_Text_Io.Get;

   package Cart_Array_Boolean_Text_Io is new
     Sal.Gen_Array_Text_Io.Enumeration_1D (
      Element_Type => Boolean,
      Index_Type => Cart_Axis_Type,
      Index_Array_Element_Type => Cart_Array_Boolean_Type,
      Element_Put => Put,
      Element_Get => Get);
   procedure Put
     (File              : in Ada.Text_IO.File_Type;
      Item              : in Cart_Array_Boolean_Type;
      Width             : in Ada.Text_IO.Field    :=
     Cart_Array_Boolean_Text_Io.Default_Width;
      Set               : in Ada.Text_IO.Type_Set :=
     Cart_Array_Boolean_Text_Io.Default_Setting;
      Single_Line       : in Boolean              :=
     Cart_Array_Boolean_Text_Io.Default_Single_Line;
      Named_Association : in Boolean              :=
     Cart_Array_Boolean_Text_Io.Default_Named_Association) renames
     Cart_Array_Boolean_Text_Io.Put;
   procedure Get
     (File              : in Ada.Text_IO.File_Type;
      Item              : out Cart_Array_Boolean_Type;
      Named_Association : in Boolean :=
     Cart_Array_Boolean_Text_Io.Default_Named_Association) renames
     Cart_Array_Boolean_Text_Io.Get;
   procedure Put
     (Item              : in Cart_Array_Boolean_Type;
      Width             : in Ada.Text_IO.Field    :=
     Cart_Array_Boolean_Text_Io.Default_Width;
      Set               : in Ada.Text_IO.Type_Set :=
     Cart_Array_Boolean_Text_Io.Default_Setting;
      Single_Line       : in Boolean              :=
     Cart_Array_Boolean_Text_Io.Default_Single_Line;
      Named_Association : in Boolean              :=
     Cart_Array_Boolean_Text_Io.Default_Named_Association) renames
     Cart_Array_Boolean_Text_Io.Put;
   procedure Get
     (Item              : out Cart_Array_Boolean_Type;
      Named_Association : in Boolean :=
     Cart_Array_Boolean_Text_Io.Default_Named_Association) renames
     Cart_Array_Boolean_Text_Io.Get;
   procedure Put_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : in Cart_Array_Boolean_Type;
      Single_Line       : in Boolean :=
     Cart_Array_Boolean_Text_Io.Default_Single_Line;
      Named_Association : in Boolean :=
     Cart_Array_Boolean_Text_Io.Default_Named_Association) renames
     Cart_Array_Boolean_Text_Io.Put_Item;
   procedure Get_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : out Cart_Array_Boolean_Type;
      Named_Association : in Boolean :=
     Cart_Array_Boolean_Text_Io.Default_Named_Association) renames
     Cart_Array_Boolean_Text_Io.Get_Item;

   package Cart_Vector_Text_Io is new Sal.Gen_Array_Text_Io.Float_1D (
      Element_Type => Real_Type,
      Index_Type => Cart_Axis_Type,
      Index_Array_Element_Type => Cart_Vector_Type,
      Element_Put => Math_Text_Io.Put,
      Element_Get => Math_Text_Io.Get);
   procedure Put
     (File              : in Ada.Text_IO.File_Type;
      Item              : in Cart_Vector_Type;
      Fore              : in Ada.Text_IO.Field :=
     Cart_Vector_Text_Io.Default_Fore;
      Aft               : in Ada.Text_IO.Field :=
     Cart_Vector_Text_Io.Default_Aft;
      Exp               : in Ada.Text_IO.Field :=
     Cart_Vector_Text_Io.Default_Exp;
      Single_Line       : in Boolean           :=
     Cart_Vector_Text_Io.Default_Single_Line;
      Named_Association : in Boolean           :=
     Cart_Vector_Text_Io.Default_Named_Association) renames
     Cart_Vector_Text_Io.Put;
   procedure Get
     (File              : in Ada.Text_IO.File_Type;
      Item              : out Cart_Vector_Type;
      Width             : in Ada.Text_IO.Field := 0;
      Named_Association : in Boolean           :=
     Cart_Vector_Text_Io.Default_Named_Association) renames
     Cart_Vector_Text_Io.Get;
   procedure Put
     (Item              : in Cart_Vector_Type;
      Fore              : in Ada.Text_IO.Field :=
     Cart_Vector_Text_Io.Default_Fore;
      Aft               : in Ada.Text_IO.Field :=
     Cart_Vector_Text_Io.Default_Aft;
      Exp               : in Ada.Text_IO.Field :=
     Cart_Vector_Text_Io.Default_Exp;
      Single_Line       : in Boolean           :=
     Cart_Vector_Text_Io.Default_Single_Line;
      Named_Association : in Boolean           :=
     Cart_Vector_Text_Io.Default_Named_Association) renames
     Cart_Vector_Text_Io.Put;
   procedure Get
     (Item              : out Cart_Vector_Type;
      Width             : in Ada.Text_IO.Field := 0;
      Named_Association : in Boolean           :=
     Cart_Vector_Text_Io.Default_Named_Association) renames
     Cart_Vector_Text_Io.Get;
   procedure Put_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : in Cart_Vector_Type;
      Single_Line       : in Boolean :=
     Cart_Vector_Text_Io.Default_Single_Line;
      Named_Association : in Boolean :=
     Cart_Vector_Text_Io.Default_Named_Association) renames
     Cart_Vector_Text_Io.Put_Item;
   procedure Get_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : out Cart_Vector_Type;
      Named_Association : in Boolean :=
     Cart_Vector_Text_Io.Default_Named_Association) renames
     Cart_Vector_Text_Io.Get_Item;

   package Cart_Array_Limit_Text_Io is new Sal.Gen_Array_Text_Io.Private_1D (
      Element_Type => Math_Scalar.Limit_Type,
      Index_Type => Cart_Axis_Type,
      Index_Array_Element_Type => Cart_Array_Limit_Type,
      Element_Put => Math_Scalar_Text_Io.Put_Item,
      Element_Get => Math_Scalar_Text_Io.Get_Item);
   procedure Put
     (File                      : in Ada.Text_IO.File_Type;
      Item                      : in Cart_Array_Limit_Type;
      Single_Line_Array         : in Boolean :=
     Cart_Array_Limit_Text_Io.Default_Single_Line_Array;
      Named_Association_Array   : in Boolean :=
     Cart_Array_Limit_Text_Io.Default_Named_Association_Array;
      Single_Line_Element       : in Boolean :=
     Cart_Array_Limit_Text_Io.Default_Single_Line_Element;
      Named_Association_Element : in Boolean :=
     Cart_Array_Limit_Text_Io.Default_Named_Association_Element) renames
     Cart_Array_Limit_Text_Io.Put;
   procedure Put
     (Item                      : in Cart_Array_Limit_Type;
      Single_Line_Array         : in Boolean :=
     Cart_Array_Limit_Text_Io.Default_Single_Line_Array;
      Named_Association_Array   : in Boolean :=
     Cart_Array_Limit_Text_Io.Default_Named_Association_Array;
      Single_Line_Element       : in Boolean :=
     Cart_Array_Limit_Text_Io.Default_Single_Line_Element;
      Named_Association_Element : in Boolean :=
     Cart_Array_Limit_Text_Io.Default_Named_Association_Element) renames
     Cart_Array_Limit_Text_Io.Put;
   procedure Put_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : in Cart_Array_Limit_Type;
      Single_Line       : in Boolean :=
     Cart_Array_Limit_Text_Io.Default_Single_Line_Array;
      Named_Association : in Boolean :=
     Cart_Array_Limit_Text_Io.Default_Named_Association_Array) renames
     Cart_Array_Limit_Text_Io.Put_Item;
   procedure Get
     (File                      : in Ada.Text_IO.File_Type;
      Item                      : out Cart_Array_Limit_Type;
      Named_Association_Array   : in Boolean :=
     Cart_Array_Limit_Text_Io.Default_Named_Association_Array;
      Named_Association_Element : in Boolean :=
     Cart_Array_Limit_Text_Io.Default_Named_Association_Element) renames
     Cart_Array_Limit_Text_Io.Get;
   procedure Get
     (Item                      : out Cart_Array_Limit_Type;
      Named_Association_Array   : in Boolean :=
     Cart_Array_Limit_Text_Io.Default_Named_Association_Array;
      Named_Association_Element : in Boolean :=
     Cart_Array_Limit_Text_Io.Default_Named_Association_Element) renames
     Cart_Array_Limit_Text_Io.Get;
   procedure Get_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : out Cart_Array_Limit_Type;
      Named_Association : in Boolean := False) renames
     Cart_Array_Limit_Text_Io.Get_Item;

   procedure Put
     (File                        : in Ada.Text_IO.File_Type;
      Item                        : in Unit_Vector_Type;
      Single_Line_Record          : in Boolean := True;
      Named_Association_Record    : in Boolean := False;
      Single_Line_Component       : in Boolean := True;
      Named_Association_Component : in Boolean := False);
   procedure Put
     (Item                        : in Unit_Vector_Type;
      Single_Line_Record          : in Boolean := True;
      Named_Association_Record    : in Boolean := False;
      Single_Line_Component       : in Boolean := True;
      Named_Association_Component : in Boolean := False);
   procedure Put_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : in Unit_Vector_Type;
      Single_Line       : in Boolean := False;
      Named_Association : in Boolean := False);

   procedure Get
     (File                        : in Ada.Text_IO.File_Type;
      Item                        : out Unit_Vector_Type;
      Named_Association_Record    : in Boolean := False;
      Named_Association_Component : in Boolean := False);
   procedure Get
     (Item                        : out Unit_Vector_Type;
      Named_Association_Record    : in Boolean := False;
      Named_Association_Component : in Boolean := False);
   procedure Get_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : out Unit_Vector_Type;
      Named_Association : in Boolean := False);

   procedure Put
     (File                        : in Ada.Text_IO.File_Type;
      Item                        : in Mag_Axis_Type;
      Single_Line_Record          : in Boolean := True;
      Named_Association_Record    : in Boolean := False;
      Single_Line_Component       : in Boolean := True;
      Named_Association_Component : in Boolean := False);
   procedure Put
     (Item                        : in Mag_Axis_Type;
      Single_Line_Record          : in Boolean := True;
      Named_Association_Record    : in Boolean := False;
      Single_Line_Component       : in Boolean := True;
      Named_Association_Component : in Boolean := False);
   procedure Put_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : in Mag_Axis_Type;
      Single_Line       : in Boolean := False;
      Named_Association : in Boolean := False);

   procedure Get
     (File                        : in Ada.Text_IO.File_Type;
      Item                        : out Mag_Axis_Type;
      Named_Association_Record    : in Boolean := False;
      Named_Association_Component : in Boolean := False);
   procedure Get
     (Item                        : out Mag_Axis_Type;
      Named_Association_Record    : in Boolean := False;
      Named_Association_Component : in Boolean := False);
   procedure Get_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : out Mag_Axis_Type;
      Named_Association : in Boolean := False);

   procedure Put
     (File                        : in Ada.Text_IO.File_Type;
      Item                        : in Unit_Quaternion_Type;
      Single_Line_Record          : in Boolean := True;
      Named_Association_Record    : in Boolean := False;
      Single_Line_Component       : in Boolean := True;
      Named_Association_Component : in Boolean := False);
   procedure Put
     (Item                        : in Unit_Quaternion_Type;
      Single_Line_Record          : in Boolean := True;
      Named_Association_Record    : in Boolean := False;
      Single_Line_Component       : in Boolean := True;
      Named_Association_Component : in Boolean := False);
   procedure Put_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : in Unit_Quaternion_Type;
      Single_Line       : in Boolean := False;
      Named_Association : in Boolean := False);

   procedure Get
     (File                        : in Ada.Text_IO.File_Type;
      Item                        : out Unit_Quaternion_Type;
      Named_Association_Record    : in Boolean := False;
      Named_Association_Component : in Boolean := False);
   procedure Get
     (Item                        : out Unit_Quaternion_Type;
      Named_Association_Record    : in Boolean := False;
      Named_Association_Component : in Boolean := False);
   procedure Get_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : out Unit_Quaternion_Type;
      Named_Association : in Boolean := False);

   procedure Put
     (File                        : in Ada.Text_IO.File_Type;
      Item                        : in Zyx_Euler_Type;
      Single_Line_Record          : in Boolean := True;
      Named_Association_Record    : in Boolean := False;
      Single_Line_Component       : in Boolean := True;
      Named_Association_Component : in Boolean := False);
   procedure Put
     (Item                        : in Zyx_Euler_Type;
      Single_Line_Record          : in Boolean := True;
      Named_Association_Record    : in Boolean := False;
      Single_Line_Component       : in Boolean := True;
      Named_Association_Component : in Boolean := False);
   procedure Put_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : in Zyx_Euler_Type;
      Single_Line       : in Boolean := False;
      Named_Association : in Boolean := False);

   procedure Get
     (File                        : in Ada.Text_IO.File_Type;
      Item                        : out Zyx_Euler_Type;
      Named_Association_Record    : in Boolean := False;
      Named_Association_Component : in Boolean := False);
   procedure Get
     (Item                        : out Zyx_Euler_Type;
      Named_Association_Record    : in Boolean := False;
      Named_Association_Component : in Boolean := False);
   procedure Get_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : out Zyx_Euler_Type;
      Named_Association : in Boolean := False);

   procedure Put
     (File                        : in Ada.Text_IO.File_Type;
      Item                        : in Celestial_Coordinate_Type;
      Single_Line_Record          : in Boolean := True;
      Named_Association_Record    : in Boolean := False;
      Single_Line_Component       : in Boolean := True;
      Named_Association_Component : in Boolean := False);
   procedure Put
     (Item                        : in Celestial_Coordinate_Type;
      Single_Line_Record          : in Boolean := True;
      Named_Association_Record    : in Boolean := False;
      Single_Line_Component       : in Boolean := True;
      Named_Association_Component : in Boolean := False);
   procedure Put_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : in Celestial_Coordinate_Type;
      Single_Line       : in Boolean := False;
      Named_Association : in Boolean := False);

   procedure Get
     (File                        : in Ada.Text_IO.File_Type;
      Item                        : out Celestial_Coordinate_Type;
      Named_Association_Record    : in Boolean := False;
      Named_Association_Component : in Boolean := False);
   procedure Get
     (Item                        : out Celestial_Coordinate_Type;
      Named_Association_Record    : in Boolean := False;
      Named_Association_Component : in Boolean := False);
   procedure Get_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : out Celestial_Coordinate_Type;
      Named_Association : in Boolean := False);

   package Cart_Array_Cart_Vector_Text_Io is new
     Sal.Gen_Array_Text_Io.Private_1D (
      Element_Type => Cart_Vector_Type,
      Index_Type => Cart_Axis_Type,
      Index_Array_Element_Type => Cart_Array_Cart_Vector_Type,
      Element_Put => Put_Item,
      Element_Get => Get_Item);
   procedure Put
     (File                      : in Ada.Text_IO.File_Type;
      Item                      : in Cart_Array_Cart_Vector_Type;
      Single_Line_Array         : in Boolean :=
     Cart_Array_Cart_Vector_Text_Io.Default_Single_Line_Array;
      Named_Association_Array   : in Boolean :=
     Cart_Array_Cart_Vector_Text_Io.Default_Named_Association_Array;
      Single_Line_Element       : in Boolean :=
     Cart_Array_Cart_Vector_Text_Io.Default_Single_Line_Element;
      Named_Association_Element : in Boolean :=
     Cart_Array_Cart_Vector_Text_Io.Default_Named_Association_Element) renames
     Cart_Array_Cart_Vector_Text_Io.Put;
   procedure Put
     (Item                      : in Cart_Array_Cart_Vector_Type;
      Single_Line_Array         : in Boolean :=
     Cart_Array_Cart_Vector_Text_Io.Default_Single_Line_Array;
      Named_Association_Array   : in Boolean :=
     Cart_Array_Cart_Vector_Text_Io.Default_Named_Association_Array;
      Single_Line_Element       : in Boolean :=
     Cart_Array_Cart_Vector_Text_Io.Default_Single_Line_Element;
      Named_Association_Element : in Boolean :=
     Cart_Array_Cart_Vector_Text_Io.Default_Named_Association_Element) renames
     Cart_Array_Cart_Vector_Text_Io.Put;
   procedure Put_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : in Cart_Array_Cart_Vector_Type;
      Single_Line       : in Boolean :=
     Cart_Array_Cart_Vector_Text_Io.Default_Single_Line_Array;
      Named_Association : in Boolean :=
     Cart_Array_Cart_Vector_Text_Io.Default_Named_Association_Array) renames
     Cart_Array_Cart_Vector_Text_Io.Put_Item;
   procedure Get
     (File                      : in Ada.Text_IO.File_Type;
      Item                      : out Cart_Array_Cart_Vector_Type;
      Named_Association_Array   : in Boolean :=
     Cart_Array_Cart_Vector_Text_Io.Default_Named_Association_Array;
      Named_Association_Element : in Boolean :=
     Cart_Array_Cart_Vector_Text_Io.Default_Named_Association_Element) renames
     Cart_Array_Cart_Vector_Text_Io.Get;
   procedure Get
     (Item                      : out Cart_Array_Cart_Vector_Type;
      Named_Association_Array   : in Boolean :=
     Cart_Array_Cart_Vector_Text_Io.Default_Named_Association_Array;
      Named_Association_Element : in Boolean :=
     Cart_Array_Cart_Vector_Text_Io.Default_Named_Association_Element) renames
     Cart_Array_Cart_Vector_Text_Io.Get;
   procedure Get_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : out Cart_Array_Cart_Vector_Type;
      Named_Association : in Boolean := False) renames
     Cart_Array_Cart_Vector_Text_Io.Get_Item;

   procedure Put
     (File                      : in Ada.Text_IO.File_Type;
      Item                      : in Rot_Matrix_Type;
      Single_Line_Array         : in Boolean := False;
      Named_Association_Array   : in Boolean := False;
      Single_Line_Element       : in Boolean := True;
      Named_Association_Element : in Boolean := False);
   procedure Put
     (Item                      : in Rot_Matrix_Type;
      Single_Line_Array         : in Boolean := False;
      Named_Association_Array   : in Boolean := False;
      Single_Line_Element       : in Boolean := True;
      Named_Association_Element : in Boolean := False);
   procedure Put_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : in Rot_Matrix_Type;
      Single_Line       : in Boolean := False;
      Named_Association : in Boolean := False);

   procedure Get
     (File                      : in Ada.Text_IO.File_Type;
      Item                      : out Rot_Matrix_Type;
      Named_Association_Array   : in Boolean := False;
      Named_Association_Element : in Boolean := False);
   procedure Get
     (Item                      : out Rot_Matrix_Type;
      Named_Association_Array   : in Boolean := False;
      Named_Association_Element : in Boolean := False);
   procedure Get_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : out Rot_Matrix_Type;
      Named_Association : in Boolean := False);

   package Inertia_Index_Text_Io is new Ada.Text_IO.Enumeration_IO (
      Inertia_Index_Type);
   procedure Put
     (File  : in Ada.Text_IO.File_Type;
      Item  : in Inertia_Index_Type;
      Width : in Ada.Text_IO.Field    := Inertia_Index_Text_Io.Default_Width;
      Set   : in Ada.Text_IO.Type_Set :=
     Inertia_Index_Text_Io.Default_Setting) renames Inertia_Index_Text_Io.Put;
   procedure Get
     (File : in Ada.Text_IO.File_Type;
      Item : out Inertia_Index_Type) renames Inertia_Index_Text_Io.Get;
   procedure Put
     (Item  : in Inertia_Index_Type;
      Width : in Ada.Text_IO.Field    := Inertia_Index_Text_Io.Default_Width;
      Set   : in Ada.Text_IO.Type_Set :=
     Inertia_Index_Text_Io.Default_Setting) renames Inertia_Index_Text_Io.Put;
   procedure Get (Item : out Inertia_Index_Type) renames
     Inertia_Index_Text_Io.Get;

   package Inertia_Text_Io is new Sal.Gen_Array_Text_Io.Float_1D (
      Element_Type => Real_Type,
      Index_Type => Inertia_Index_Type,
      Index_Array_Element_Type => Inertia_Type,
      Element_Put => Math_Text_Io.Put,
      Element_Get => Math_Text_Io.Get);
   procedure Put
     (File              : in Ada.Text_IO.File_Type;
      Item              : in Inertia_Type;
      Fore              : in Ada.Text_IO.Field :=
     Inertia_Text_Io.Default_Fore;
      Aft               : in Ada.Text_IO.Field := Inertia_Text_Io.Default_Aft;
      Exp               : in Ada.Text_IO.Field := Inertia_Text_Io.Default_Exp;
      Single_Line       : in Boolean           :=
     Inertia_Text_Io.Default_Single_Line;
      Named_Association : in Boolean           :=
     Inertia_Text_Io.Default_Named_Association) renames Inertia_Text_Io.Put;
   procedure Get
     (File              : in Ada.Text_IO.File_Type;
      Item              : out Inertia_Type;
      Width             : in Ada.Text_IO.Field := 0;
      Named_Association : in Boolean           :=
     Inertia_Text_Io.Default_Named_Association) renames Inertia_Text_Io.Get;
   procedure Put
     (Item              : in Inertia_Type;
      Fore              : in Ada.Text_IO.Field :=
     Inertia_Text_Io.Default_Fore;
      Aft               : in Ada.Text_IO.Field := Inertia_Text_Io.Default_Aft;
      Exp               : in Ada.Text_IO.Field := Inertia_Text_Io.Default_Exp;
      Single_Line       : in Boolean           :=
     Inertia_Text_Io.Default_Single_Line;
      Named_Association : in Boolean           :=
     Inertia_Text_Io.Default_Named_Association) renames Inertia_Text_Io.Put;
   procedure Get
     (Item              : out Inertia_Type;
      Width             : in Ada.Text_IO.Field := 0;
      Named_Association : in Boolean           :=
     Inertia_Text_Io.Default_Named_Association) renames Inertia_Text_Io.Get;
   procedure Put_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : in Inertia_Type;
      Single_Line       : in Boolean := Inertia_Text_Io.Default_Single_Line;
      Named_Association : in Boolean :=
     Inertia_Text_Io.Default_Named_Association) renames
     Inertia_Text_Io.Put_Item;
   procedure Get_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : out Inertia_Type;
      Named_Association : in Boolean :=
     Inertia_Text_Io.Default_Named_Association) renames
     Inertia_Text_Io.Get_Item;

   package Inverse_Inertia_Text_Io is new Sal.Gen_Array_Text_Io.Float_1D (
      Element_Type => Real_Type,
      Index_Type => Inertia_Index_Type,
      Index_Array_Element_Type => Inverse_Inertia_Type,
      Element_Put => Math_Text_Io.Put,
      Element_Get => Math_Text_Io.Get);
   procedure Put
     (File              : in Ada.Text_IO.File_Type;
      Item              : in Inverse_Inertia_Type;
      Fore              : in Ada.Text_IO.Field :=
     Inverse_Inertia_Text_Io.Default_Fore;
      Aft               : in Ada.Text_IO.Field :=
     Inverse_Inertia_Text_Io.Default_Aft;
      Exp               : in Ada.Text_IO.Field :=
     Inverse_Inertia_Text_Io.Default_Exp;
      Single_Line       : in Boolean           :=
     Inverse_Inertia_Text_Io.Default_Single_Line;
      Named_Association : in Boolean           :=
     Inverse_Inertia_Text_Io.Default_Named_Association) renames
     Inverse_Inertia_Text_Io.Put;
   procedure Get
     (File              : in Ada.Text_IO.File_Type;
      Item              : out Inverse_Inertia_Type;
      Width             : in Ada.Text_IO.Field := 0;
      Named_Association : in Boolean           :=
     Inverse_Inertia_Text_Io.Default_Named_Association) renames
     Inverse_Inertia_Text_Io.Get;
   procedure Put
     (Item              : in Inverse_Inertia_Type;
      Fore              : in Ada.Text_IO.Field :=
     Inverse_Inertia_Text_Io.Default_Fore;
      Aft               : in Ada.Text_IO.Field :=
     Inverse_Inertia_Text_Io.Default_Aft;
      Exp               : in Ada.Text_IO.Field :=
     Inverse_Inertia_Text_Io.Default_Exp;
      Single_Line       : in Boolean           :=
     Inverse_Inertia_Text_Io.Default_Single_Line;
      Named_Association : in Boolean           :=
     Inverse_Inertia_Text_Io.Default_Named_Association) renames
     Inverse_Inertia_Text_Io.Put;
   procedure Get
     (Item              : out Inverse_Inertia_Type;
      Width             : in Ada.Text_IO.Field := 0;
      Named_Association : in Boolean           :=
     Inverse_Inertia_Text_Io.Default_Named_Association) renames
     Inverse_Inertia_Text_Io.Get;
   procedure Put_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : in Inverse_Inertia_Type;
      Single_Line       : in Boolean :=
     Inverse_Inertia_Text_Io.Default_Single_Line;
      Named_Association : in Boolean :=
     Inverse_Inertia_Text_Io.Default_Named_Association) renames
     Inverse_Inertia_Text_Io.Put_Item;
   procedure Get_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : out Inverse_Inertia_Type;
      Named_Association : in Boolean :=
     Inverse_Inertia_Text_Io.Default_Named_Association) renames
     Inverse_Inertia_Text_Io.Get_Item;

end Sal.Gen_Math.Gen_Dof_3.Gen_Text_Io;
