--  Abstract :
--
--  Text_IO for types in SAL.Gen_Math.Gen_Manipulator
--
--  This file is auto-generated by auto_text_io
--  from SAL.Gen_Math.Gen_Manipulator
--
with Boolean_Text_IO;                       use Boolean_Text_IO;
with Sal.Gen_Array_Text_Io;
with Sal.Gen_Math.Gen_Dof_3.Gen_Text_Io;
with Sal.Gen_Math.Gen_Dof_6.Gen_Text_Io;
with Sal.Gen_Math.Gen_Den_Hart.Gen_Text_Io;
with Sal.Gen_Math.Gen_Scalar.Gen_Text_Io;
with Sal.Gen_Math.Gen_Text_Io;
with Ada.Text_IO;
generic
   with package Math_Text_Io is new Sal.Gen_Math.Gen_Text_Io;
   with package Math_Scalar_Text_Io is new Parent_Math_Scalar.Gen_Text_Io (
      Math_Text_Io);
   with package Math_Dof_3_Text_Io is new Parent_Math_Dof_3.Gen_Text_Io (
      Math_Text_Io,
      Math_Scalar_Text_Io);
   with package Math_Dof_6_Text_Io is new Parent_Math_Dof_6.Gen_Text_Io (
      Math_Text_Io,
      Math_Scalar_Text_Io,
      Math_Dof_3_Text_Io);
   with package Math_Den_Hart_Text_Io is new Parent_Math_Den_Hart.Gen_Text_Io (
      Math_Text_Io,
      Math_Scalar_Text_Io);
package Sal.Gen_Math.Gen_Manipulator.Gen_Text_Io is
   pragma Elaborate_Body;

   package Joint_Index_Text_Io is new Ada.Text_IO.Enumeration_IO (
      Joint_Index_Type);
   procedure Put
     (File  : in Ada.Text_IO.File_Type;
      Item  : in Joint_Index_Type;
      Width : in Ada.Text_IO.Field    := Joint_Index_Text_Io.Default_Width;
      Set   : in Ada.Text_IO.Type_Set := Joint_Index_Text_Io.Default_Setting) 
renames Joint_Index_Text_Io.Put;
   procedure Get
     (File : in Ada.Text_IO.File_Type;
      Item : out Joint_Index_Type) renames Joint_Index_Text_Io.Get;
   procedure Put
     (Item  : in Joint_Index_Type;
      Width : in Ada.Text_IO.Field    := Joint_Index_Text_Io.Default_Width;
      Set   : in Ada.Text_IO.Type_Set := Joint_Index_Text_Io.Default_Setting) 
renames Joint_Index_Text_Io.Put;
   procedure Get (Item : out Joint_Index_Type) renames Joint_Index_Text_Io.Get;

   package Joint_Array_Boolean_Text_Io is new
     Sal.Gen_Array_Text_Io.Enumeration_1D (
      Element_Type => Boolean,
      Index_Type => Joint_Index_Type,
      Index_Array_Element_Type => Joint_Array_Boolean_Type,
      Element_Put => Put,
      Element_Get => Get);
   procedure Put
     (File              : in Ada.Text_IO.File_Type;
      Item              : in Joint_Array_Boolean_Type;
      Width             : in Ada.Text_IO.Field    :=
     Joint_Array_Boolean_Text_Io.Default_Width;
      Set               : in Ada.Text_IO.Type_Set :=
     Joint_Array_Boolean_Text_Io.Default_Setting;
      Single_Line       : in Boolean              :=
     Joint_Array_Boolean_Text_Io.Default_Single_Line;
      Named_Association : in Boolean              :=
     Joint_Array_Boolean_Text_Io.Default_Named_Association) renames
     Joint_Array_Boolean_Text_Io.Put;
   procedure Get
     (File              : in Ada.Text_IO.File_Type;
      Item              : out Joint_Array_Boolean_Type;
      Named_Association : in Boolean :=
     Joint_Array_Boolean_Text_Io.Default_Named_Association) renames
     Joint_Array_Boolean_Text_Io.Get;
   procedure Put
     (Item              : in Joint_Array_Boolean_Type;
      Width             : in Ada.Text_IO.Field    :=
     Joint_Array_Boolean_Text_Io.Default_Width;
      Set               : in Ada.Text_IO.Type_Set :=
     Joint_Array_Boolean_Text_Io.Default_Setting;
      Single_Line       : in Boolean              :=
     Joint_Array_Boolean_Text_Io.Default_Single_Line;
      Named_Association : in Boolean              :=
     Joint_Array_Boolean_Text_Io.Default_Named_Association) renames
     Joint_Array_Boolean_Text_Io.Put;
   procedure Get
     (Item              : out Joint_Array_Boolean_Type;
      Named_Association : in Boolean :=
     Joint_Array_Boolean_Text_Io.Default_Named_Association) renames
     Joint_Array_Boolean_Text_Io.Get;
   procedure Put_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : in Joint_Array_Boolean_Type;
      Single_Line       : in Boolean :=
     Joint_Array_Boolean_Text_Io.Default_Single_Line;
      Named_Association : in Boolean :=
     Joint_Array_Boolean_Text_Io.Default_Named_Association) renames
     Joint_Array_Boolean_Text_Io.Put_Item;
   procedure Get_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : out Joint_Array_Boolean_Type;
      Named_Association : in Boolean :=
     Joint_Array_Boolean_Text_Io.Default_Named_Association) renames
     Joint_Array_Boolean_Text_Io.Get_Item;

   package Joint_Array_Real_Text_Io is new Sal.Gen_Array_Text_Io.Float_1D (
      Element_Type => Real_Type,
      Index_Type => Joint_Index_Type,
      Index_Array_Element_Type => Joint_Array_Real_Type,
      Element_Put => Math_Text_Io.Put,
      Element_Get => Math_Text_Io.Get);
   procedure Put
     (File              : in Ada.Text_IO.File_Type;
      Item              : in Joint_Array_Real_Type;
      Fore              : in Ada.Text_IO.Field :=
     Joint_Array_Real_Text_Io.Default_Fore;
      Aft               : in Ada.Text_IO.Field :=
     Joint_Array_Real_Text_Io.Default_Aft;
      Exp               : in Ada.Text_IO.Field :=
     Joint_Array_Real_Text_Io.Default_Exp;
      Single_Line       : in Boolean           :=
     Joint_Array_Real_Text_Io.Default_Single_Line;
      Named_Association : in Boolean           :=
     Joint_Array_Real_Text_Io.Default_Named_Association) renames
     Joint_Array_Real_Text_Io.Put;
   procedure Get
     (File              : in Ada.Text_IO.File_Type;
      Item              : out Joint_Array_Real_Type;
      Width             : in Ada.Text_IO.Field := 0;
      Named_Association : in Boolean           :=
     Joint_Array_Real_Text_Io.Default_Named_Association) renames
     Joint_Array_Real_Text_Io.Get;
   procedure Put
     (Item              : in Joint_Array_Real_Type;
      Fore              : in Ada.Text_IO.Field :=
     Joint_Array_Real_Text_Io.Default_Fore;
      Aft               : in Ada.Text_IO.Field :=
     Joint_Array_Real_Text_Io.Default_Aft;
      Exp               : in Ada.Text_IO.Field :=
     Joint_Array_Real_Text_Io.Default_Exp;
      Single_Line       : in Boolean           :=
     Joint_Array_Real_Text_Io.Default_Single_Line;
      Named_Association : in Boolean           :=
     Joint_Array_Real_Text_Io.Default_Named_Association) renames
     Joint_Array_Real_Text_Io.Put;
   procedure Get
     (Item              : out Joint_Array_Real_Type;
      Width             : in Ada.Text_IO.Field := 0;
      Named_Association : in Boolean           :=
     Joint_Array_Real_Text_Io.Default_Named_Association) renames
     Joint_Array_Real_Text_Io.Get;
   procedure Put_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : in Joint_Array_Real_Type;
      Single_Line       : in Boolean :=
     Joint_Array_Real_Text_Io.Default_Single_Line;
      Named_Association : in Boolean :=
     Joint_Array_Real_Text_Io.Default_Named_Association) renames
     Joint_Array_Real_Text_Io.Put_Item;
   procedure Get_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : out Joint_Array_Real_Type;
      Named_Association : in Boolean :=
     Joint_Array_Real_Text_Io.Default_Named_Association) renames
     Joint_Array_Real_Text_Io.Get_Item;

   package Joint_Array_Limit_Text_Io is new Sal.Gen_Array_Text_Io.Private_1D (
      Element_Type => Math_Scalar.Limit_Type,
      Index_Type => Joint_Index_Type,
      Index_Array_Element_Type => Joint_Array_Limit_Type,
      Element_Put => Math_Scalar_Text_Io.Put_Item,
      Element_Get => Math_Scalar_Text_Io.Get_Item);
   procedure Put
     (File                      : in Ada.Text_IO.File_Type;
      Item                      : in Joint_Array_Limit_Type;
      Single_Line_Array         : in Boolean :=
     Joint_Array_Limit_Text_Io.Default_Single_Line_Array;
      Named_Association_Array   : in Boolean :=
     Joint_Array_Limit_Text_Io.Default_Named_Association_Array;
      Single_Line_Element       : in Boolean :=
     Joint_Array_Limit_Text_Io.Default_Single_Line_Element;
      Named_Association_Element : in Boolean :=
     Joint_Array_Limit_Text_Io.Default_Named_Association_Element) renames
     Joint_Array_Limit_Text_Io.Put;
   procedure Put
     (Item                      : in Joint_Array_Limit_Type;
      Single_Line_Array         : in Boolean :=
     Joint_Array_Limit_Text_Io.Default_Single_Line_Array;
      Named_Association_Array   : in Boolean :=
     Joint_Array_Limit_Text_Io.Default_Named_Association_Array;
      Single_Line_Element       : in Boolean :=
     Joint_Array_Limit_Text_Io.Default_Single_Line_Element;
      Named_Association_Element : in Boolean :=
     Joint_Array_Limit_Text_Io.Default_Named_Association_Element) renames
     Joint_Array_Limit_Text_Io.Put;
   procedure Put_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : in Joint_Array_Limit_Type;
      Single_Line       : in Boolean :=
     Joint_Array_Limit_Text_Io.Default_Single_Line_Array;
      Named_Association : in Boolean :=
     Joint_Array_Limit_Text_Io.Default_Named_Association_Array) renames
     Joint_Array_Limit_Text_Io.Put_Item;
   procedure Get
     (File                      : in Ada.Text_IO.File_Type;
      Item                      : out Joint_Array_Limit_Type;
      Named_Association_Array   : in Boolean :=
     Joint_Array_Limit_Text_Io.Default_Named_Association_Array;
      Named_Association_Element : in Boolean :=
     Joint_Array_Limit_Text_Io.Default_Named_Association_Element) renames
     Joint_Array_Limit_Text_Io.Get;
   procedure Get
     (Item                      : out Joint_Array_Limit_Type;
      Named_Association_Array   : in Boolean :=
     Joint_Array_Limit_Text_Io.Default_Named_Association_Array;
      Named_Association_Element : in Boolean :=
     Joint_Array_Limit_Text_Io.Default_Named_Association_Element) renames
     Joint_Array_Limit_Text_Io.Get;
   procedure Get_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : out Joint_Array_Limit_Type;
      Named_Association : in Boolean := False) renames
     Joint_Array_Limit_Text_Io.Get_Item;

   package Joint_Array_Jar_Text_Io is new Sal.Gen_Array_Text_Io.Private_1D (
      Element_Type => Joint_Array_Real_Type,
      Index_Type => Joint_Index_Type,
      Index_Array_Element_Type => Joint_Array_Jar_Type,
      Element_Put => Put_Item,
      Element_Get => Get_Item);
   procedure Put
     (File                      : in Ada.Text_IO.File_Type;
      Item                      : in Joint_Array_Jar_Type;
      Single_Line_Array         : in Boolean :=
     Joint_Array_Jar_Text_Io.Default_Single_Line_Array;
      Named_Association_Array   : in Boolean :=
     Joint_Array_Jar_Text_Io.Default_Named_Association_Array;
      Single_Line_Element       : in Boolean :=
     Joint_Array_Jar_Text_Io.Default_Single_Line_Element;
      Named_Association_Element : in Boolean :=
     Joint_Array_Jar_Text_Io.Default_Named_Association_Element) renames
     Joint_Array_Jar_Text_Io.Put;
   procedure Put
     (Item                      : in Joint_Array_Jar_Type;
      Single_Line_Array         : in Boolean :=
     Joint_Array_Jar_Text_Io.Default_Single_Line_Array;
      Named_Association_Array   : in Boolean :=
     Joint_Array_Jar_Text_Io.Default_Named_Association_Array;
      Single_Line_Element       : in Boolean :=
     Joint_Array_Jar_Text_Io.Default_Single_Line_Element;
      Named_Association_Element : in Boolean :=
     Joint_Array_Jar_Text_Io.Default_Named_Association_Element) renames
     Joint_Array_Jar_Text_Io.Put;
   procedure Put_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : in Joint_Array_Jar_Type;
      Single_Line       : in Boolean :=
     Joint_Array_Jar_Text_Io.Default_Single_Line_Array;
      Named_Association : in Boolean :=
     Joint_Array_Jar_Text_Io.Default_Named_Association_Array) renames
     Joint_Array_Jar_Text_Io.Put_Item;
   procedure Get
     (File                      : in Ada.Text_IO.File_Type;
      Item                      : out Joint_Array_Jar_Type;
      Named_Association_Array   : in Boolean :=
     Joint_Array_Jar_Text_Io.Default_Named_Association_Array;
      Named_Association_Element : in Boolean :=
     Joint_Array_Jar_Text_Io.Default_Named_Association_Element) renames
     Joint_Array_Jar_Text_Io.Get;
   procedure Get
     (Item                      : out Joint_Array_Jar_Type;
      Named_Association_Array   : in Boolean :=
     Joint_Array_Jar_Text_Io.Default_Named_Association_Array;
      Named_Association_Element : in Boolean :=
     Joint_Array_Jar_Text_Io.Default_Named_Association_Element) renames
     Joint_Array_Jar_Text_Io.Get;
   procedure Get_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : out Joint_Array_Jar_Type;
      Named_Association : in Boolean := False) renames
     Joint_Array_Jar_Text_Io.Get_Item;

   package Joint_Array_Den_Hart_Text_Io is new
     Sal.Gen_Array_Text_Io.Private_1D (
      Element_Type => Math_Den_Hart.Den_Hart_Type,
      Index_Type => Joint_Index_Type,
      Index_Array_Element_Type => Joint_Array_Den_Hart_Type,
      Element_Put => Math_Den_Hart_Text_Io.Put_Item,
      Element_Get => Math_Den_Hart_Text_Io.Get_Item);
   procedure Put
     (File                      : in Ada.Text_IO.File_Type;
      Item                      : in Joint_Array_Den_Hart_Type;
      Single_Line_Array         : in Boolean :=
     Joint_Array_Den_Hart_Text_Io.Default_Single_Line_Array;
      Named_Association_Array   : in Boolean :=
     Joint_Array_Den_Hart_Text_Io.Default_Named_Association_Array;
      Single_Line_Element       : in Boolean :=
     Joint_Array_Den_Hart_Text_Io.Default_Single_Line_Element;
      Named_Association_Element : in Boolean :=
     Joint_Array_Den_Hart_Text_Io.Default_Named_Association_Element) renames
     Joint_Array_Den_Hart_Text_Io.Put;
   procedure Put
     (Item                      : in Joint_Array_Den_Hart_Type;
      Single_Line_Array         : in Boolean :=
     Joint_Array_Den_Hart_Text_Io.Default_Single_Line_Array;
      Named_Association_Array   : in Boolean :=
     Joint_Array_Den_Hart_Text_Io.Default_Named_Association_Array;
      Single_Line_Element       : in Boolean :=
     Joint_Array_Den_Hart_Text_Io.Default_Single_Line_Element;
      Named_Association_Element : in Boolean :=
     Joint_Array_Den_Hart_Text_Io.Default_Named_Association_Element) renames
     Joint_Array_Den_Hart_Text_Io.Put;
   procedure Put_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : in Joint_Array_Den_Hart_Type;
      Single_Line       : in Boolean :=
     Joint_Array_Den_Hart_Text_Io.Default_Single_Line_Array;
      Named_Association : in Boolean :=
     Joint_Array_Den_Hart_Text_Io.Default_Named_Association_Array) renames
     Joint_Array_Den_Hart_Text_Io.Put_Item;
   procedure Get
     (File                      : in Ada.Text_IO.File_Type;
      Item                      : out Joint_Array_Den_Hart_Type;
      Named_Association_Array   : in Boolean :=
     Joint_Array_Den_Hart_Text_Io.Default_Named_Association_Array;
      Named_Association_Element : in Boolean :=
     Joint_Array_Den_Hart_Text_Io.Default_Named_Association_Element) renames
     Joint_Array_Den_Hart_Text_Io.Get;
   procedure Get
     (Item                      : out Joint_Array_Den_Hart_Type;
      Named_Association_Array   : in Boolean :=
     Joint_Array_Den_Hart_Text_Io.Default_Named_Association_Array;
      Named_Association_Element : in Boolean :=
     Joint_Array_Den_Hart_Text_Io.Default_Named_Association_Element) renames
     Joint_Array_Den_Hart_Text_Io.Get;
   procedure Get_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : out Joint_Array_Den_Hart_Type;
      Named_Association : in Boolean := False) renames
     Joint_Array_Den_Hart_Text_Io.Get_Item;

   package Joint_Array_Pose_Text_Io is new Sal.Gen_Array_Text_Io.Private_1D (
      Element_Type => Math_Dof_6.Pose_Type,
      Index_Type => Joint_Index_Type,
      Index_Array_Element_Type => Joint_Array_Pose_Type,
      Element_Put => Math_Dof_6_Text_Io.Put_Item,
      Element_Get => Math_Dof_6_Text_Io.Get_Item);
   procedure Put
     (File                      : in Ada.Text_IO.File_Type;
      Item                      : in Joint_Array_Pose_Type;
      Single_Line_Array         : in Boolean :=
     Joint_Array_Pose_Text_Io.Default_Single_Line_Array;
      Named_Association_Array   : in Boolean :=
     Joint_Array_Pose_Text_Io.Default_Named_Association_Array;
      Single_Line_Element       : in Boolean :=
     Joint_Array_Pose_Text_Io.Default_Single_Line_Element;
      Named_Association_Element : in Boolean :=
     Joint_Array_Pose_Text_Io.Default_Named_Association_Element) renames
     Joint_Array_Pose_Text_Io.Put;
   procedure Put
     (Item                      : in Joint_Array_Pose_Type;
      Single_Line_Array         : in Boolean :=
     Joint_Array_Pose_Text_Io.Default_Single_Line_Array;
      Named_Association_Array   : in Boolean :=
     Joint_Array_Pose_Text_Io.Default_Named_Association_Array;
      Single_Line_Element       : in Boolean :=
     Joint_Array_Pose_Text_Io.Default_Single_Line_Element;
      Named_Association_Element : in Boolean :=
     Joint_Array_Pose_Text_Io.Default_Named_Association_Element) renames
     Joint_Array_Pose_Text_Io.Put;
   procedure Put_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : in Joint_Array_Pose_Type;
      Single_Line       : in Boolean :=
     Joint_Array_Pose_Text_Io.Default_Single_Line_Array;
      Named_Association : in Boolean :=
     Joint_Array_Pose_Text_Io.Default_Named_Association_Array) renames
     Joint_Array_Pose_Text_Io.Put_Item;
   procedure Get
     (File                      : in Ada.Text_IO.File_Type;
      Item                      : out Joint_Array_Pose_Type;
      Named_Association_Array   : in Boolean :=
     Joint_Array_Pose_Text_Io.Default_Named_Association_Array;
      Named_Association_Element : in Boolean :=
     Joint_Array_Pose_Text_Io.Default_Named_Association_Element) renames
     Joint_Array_Pose_Text_Io.Get;
   procedure Get
     (Item                      : out Joint_Array_Pose_Type;
      Named_Association_Array   : in Boolean :=
     Joint_Array_Pose_Text_Io.Default_Named_Association_Array;
      Named_Association_Element : in Boolean :=
     Joint_Array_Pose_Text_Io.Default_Named_Association_Element) renames
     Joint_Array_Pose_Text_Io.Get;
   procedure Get_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : out Joint_Array_Pose_Type;
      Named_Association : in Boolean := False) renames
     Joint_Array_Pose_Text_Io.Get_Item;

   package Joint_Array_Mass_Text_Io is new Sal.Gen_Array_Text_Io.Private_1D (
      Element_Type => Math_Dof_6.Mass_Type,
      Index_Type => Joint_Index_Type,
      Index_Array_Element_Type => Joint_Array_Mass_Type,
      Element_Put => Math_Dof_6_Text_Io.Put_Item,
      Element_Get => Math_Dof_6_Text_Io.Get_Item);
   procedure Put
     (File                      : in Ada.Text_IO.File_Type;
      Item                      : in Joint_Array_Mass_Type;
      Single_Line_Array         : in Boolean :=
     Joint_Array_Mass_Text_Io.Default_Single_Line_Array;
      Named_Association_Array   : in Boolean :=
     Joint_Array_Mass_Text_Io.Default_Named_Association_Array;
      Single_Line_Element       : in Boolean :=
     Joint_Array_Mass_Text_Io.Default_Single_Line_Element;
      Named_Association_Element : in Boolean :=
     Joint_Array_Mass_Text_Io.Default_Named_Association_Element) renames
     Joint_Array_Mass_Text_Io.Put;
   procedure Put
     (Item                      : in Joint_Array_Mass_Type;
      Single_Line_Array         : in Boolean :=
     Joint_Array_Mass_Text_Io.Default_Single_Line_Array;
      Named_Association_Array   : in Boolean :=
     Joint_Array_Mass_Text_Io.Default_Named_Association_Array;
      Single_Line_Element       : in Boolean :=
     Joint_Array_Mass_Text_Io.Default_Single_Line_Element;
      Named_Association_Element : in Boolean :=
     Joint_Array_Mass_Text_Io.Default_Named_Association_Element) renames
     Joint_Array_Mass_Text_Io.Put;
   procedure Put_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : in Joint_Array_Mass_Type;
      Single_Line       : in Boolean :=
     Joint_Array_Mass_Text_Io.Default_Single_Line_Array;
      Named_Association : in Boolean :=
     Joint_Array_Mass_Text_Io.Default_Named_Association_Array) renames
     Joint_Array_Mass_Text_Io.Put_Item;
   procedure Get
     (File                      : in Ada.Text_IO.File_Type;
      Item                      : out Joint_Array_Mass_Type;
      Named_Association_Array   : in Boolean :=
     Joint_Array_Mass_Text_Io.Default_Named_Association_Array;
      Named_Association_Element : in Boolean :=
     Joint_Array_Mass_Text_Io.Default_Named_Association_Element) renames
     Joint_Array_Mass_Text_Io.Get;
   procedure Get
     (Item                      : out Joint_Array_Mass_Type;
      Named_Association_Array   : in Boolean :=
     Joint_Array_Mass_Text_Io.Default_Named_Association_Array;
      Named_Association_Element : in Boolean :=
     Joint_Array_Mass_Text_Io.Default_Named_Association_Element) renames
     Joint_Array_Mass_Text_Io.Get;
   procedure Get_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : out Joint_Array_Mass_Type;
      Named_Association : in Boolean := False) renames
     Joint_Array_Mass_Text_Io.Get_Item;

   package Joint_Array_Dcv_Text_Io is new Sal.Gen_Array_Text_Io.Private_1D (
      Element_Type => Math_Dof_6.Dual_Cart_Vector_Type,
      Index_Type => Joint_Index_Type,
      Index_Array_Element_Type => Joint_Array_Dcv_Type,
      Element_Put => Math_Dof_6_Text_Io.Put_Item,
      Element_Get => Math_Dof_6_Text_Io.Get_Item);
   procedure Put
     (File                      : in Ada.Text_IO.File_Type;
      Item                      : in Joint_Array_Dcv_Type;
      Single_Line_Array         : in Boolean :=
     Joint_Array_Dcv_Text_Io.Default_Single_Line_Array;
      Named_Association_Array   : in Boolean :=
     Joint_Array_Dcv_Text_Io.Default_Named_Association_Array;
      Single_Line_Element       : in Boolean :=
     Joint_Array_Dcv_Text_Io.Default_Single_Line_Element;
      Named_Association_Element : in Boolean :=
     Joint_Array_Dcv_Text_Io.Default_Named_Association_Element) renames
     Joint_Array_Dcv_Text_Io.Put;
   procedure Put
     (Item                      : in Joint_Array_Dcv_Type;
      Single_Line_Array         : in Boolean :=
     Joint_Array_Dcv_Text_Io.Default_Single_Line_Array;
      Named_Association_Array   : in Boolean :=
     Joint_Array_Dcv_Text_Io.Default_Named_Association_Array;
      Single_Line_Element       : in Boolean :=
     Joint_Array_Dcv_Text_Io.Default_Single_Line_Element;
      Named_Association_Element : in Boolean :=
     Joint_Array_Dcv_Text_Io.Default_Named_Association_Element) renames
     Joint_Array_Dcv_Text_Io.Put;
   procedure Put_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : in Joint_Array_Dcv_Type;
      Single_Line       : in Boolean :=
     Joint_Array_Dcv_Text_Io.Default_Single_Line_Array;
      Named_Association : in Boolean :=
     Joint_Array_Dcv_Text_Io.Default_Named_Association_Array) renames
     Joint_Array_Dcv_Text_Io.Put_Item;
   procedure Get
     (File                      : in Ada.Text_IO.File_Type;
      Item                      : out Joint_Array_Dcv_Type;
      Named_Association_Array   : in Boolean :=
     Joint_Array_Dcv_Text_Io.Default_Named_Association_Array;
      Named_Association_Element : in Boolean :=
     Joint_Array_Dcv_Text_Io.Default_Named_Association_Element) renames
     Joint_Array_Dcv_Text_Io.Get;
   procedure Get
     (Item                      : out Joint_Array_Dcv_Type;
      Named_Association_Array   : in Boolean :=
     Joint_Array_Dcv_Text_Io.Default_Named_Association_Array;
      Named_Association_Element : in Boolean :=
     Joint_Array_Dcv_Text_Io.Default_Named_Association_Element) renames
     Joint_Array_Dcv_Text_Io.Get;
   procedure Get_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : out Joint_Array_Dcv_Type;
      Named_Association : in Boolean := False) renames
     Joint_Array_Dcv_Text_Io.Get_Item;

   package Dc_Array_Jar_Text_Io is new Sal.Gen_Array_Text_Io.Private_1D (
      Element_Type => Joint_Array_Real_Type,
      Index_Type => Math_Dof_6.Dual_Cart_Axis_Type,
      Index_Array_Element_Type => Dc_Array_Jar_Type,
      Element_Put => Put_Item,
      Element_Get => Get_Item);
   procedure Put
     (File                      : in Ada.Text_IO.File_Type;
      Item                      : in Dc_Array_Jar_Type;
      Single_Line_Array         : in Boolean :=
     Dc_Array_Jar_Text_Io.Default_Single_Line_Array;
      Named_Association_Array   : in Boolean :=
     Dc_Array_Jar_Text_Io.Default_Named_Association_Array;
      Single_Line_Element       : in Boolean :=
     Dc_Array_Jar_Text_Io.Default_Single_Line_Element;
      Named_Association_Element : in Boolean :=
     Dc_Array_Jar_Text_Io.Default_Named_Association_Element) renames
     Dc_Array_Jar_Text_Io.Put;
   procedure Put
     (Item                      : in Dc_Array_Jar_Type;
      Single_Line_Array         : in Boolean :=
     Dc_Array_Jar_Text_Io.Default_Single_Line_Array;
      Named_Association_Array   : in Boolean :=
     Dc_Array_Jar_Text_Io.Default_Named_Association_Array;
      Single_Line_Element       : in Boolean :=
     Dc_Array_Jar_Text_Io.Default_Single_Line_Element;
      Named_Association_Element : in Boolean :=
     Dc_Array_Jar_Text_Io.Default_Named_Association_Element) renames
     Dc_Array_Jar_Text_Io.Put;
   procedure Put_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : in Dc_Array_Jar_Type;
      Single_Line       : in Boolean :=
     Dc_Array_Jar_Text_Io.Default_Single_Line_Array;
      Named_Association : in Boolean :=
     Dc_Array_Jar_Text_Io.Default_Named_Association_Array) renames
     Dc_Array_Jar_Text_Io.Put_Item;
   procedure Get
     (File                      : in Ada.Text_IO.File_Type;
      Item                      : out Dc_Array_Jar_Type;
      Named_Association_Array   : in Boolean :=
     Dc_Array_Jar_Text_Io.Default_Named_Association_Array;
      Named_Association_Element : in Boolean :=
     Dc_Array_Jar_Text_Io.Default_Named_Association_Element) renames
     Dc_Array_Jar_Text_Io.Get;
   procedure Get
     (Item                      : out Dc_Array_Jar_Type;
      Named_Association_Array   : in Boolean :=
     Dc_Array_Jar_Text_Io.Default_Named_Association_Array;
      Named_Association_Element : in Boolean :=
     Dc_Array_Jar_Text_Io.Default_Named_Association_Element) renames
     Dc_Array_Jar_Text_Io.Get;
   procedure Get_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : out Dc_Array_Jar_Type;
      Named_Association : in Boolean := False) renames
     Dc_Array_Jar_Text_Io.Get_Item;

   package Joint_Array_Trig_Pair_Text_Io is new
     Sal.Gen_Array_Text_Io.Private_1D (
      Element_Type => Math_Scalar.Trig_Pair_Type,
      Index_Type => Joint_Index_Type,
      Index_Array_Element_Type => Joint_Array_Trig_Pair_Type,
      Element_Put => Math_Scalar_Text_Io.Put_Item,
      Element_Get => Math_Scalar_Text_Io.Get_Item);
   procedure Put
     (File                      : in Ada.Text_IO.File_Type;
      Item                      : in Joint_Array_Trig_Pair_Type;
      Single_Line_Array         : in Boolean :=
     Joint_Array_Trig_Pair_Text_Io.Default_Single_Line_Array;
      Named_Association_Array   : in Boolean :=
     Joint_Array_Trig_Pair_Text_Io.Default_Named_Association_Array;
      Single_Line_Element       : in Boolean :=
     Joint_Array_Trig_Pair_Text_Io.Default_Single_Line_Element;
      Named_Association_Element : in Boolean :=
     Joint_Array_Trig_Pair_Text_Io.Default_Named_Association_Element) renames
     Joint_Array_Trig_Pair_Text_Io.Put;
   procedure Put
     (Item                      : in Joint_Array_Trig_Pair_Type;
      Single_Line_Array         : in Boolean :=
     Joint_Array_Trig_Pair_Text_Io.Default_Single_Line_Array;
      Named_Association_Array   : in Boolean :=
     Joint_Array_Trig_Pair_Text_Io.Default_Named_Association_Array;
      Single_Line_Element       : in Boolean :=
     Joint_Array_Trig_Pair_Text_Io.Default_Single_Line_Element;
      Named_Association_Element : in Boolean :=
     Joint_Array_Trig_Pair_Text_Io.Default_Named_Association_Element) renames
     Joint_Array_Trig_Pair_Text_Io.Put;
   procedure Put_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : in Joint_Array_Trig_Pair_Type;
      Single_Line       : in Boolean :=
     Joint_Array_Trig_Pair_Text_Io.Default_Single_Line_Array;
      Named_Association : in Boolean :=
     Joint_Array_Trig_Pair_Text_Io.Default_Named_Association_Array) renames
     Joint_Array_Trig_Pair_Text_Io.Put_Item;
   procedure Get
     (File                      : in Ada.Text_IO.File_Type;
      Item                      : out Joint_Array_Trig_Pair_Type;
      Named_Association_Array   : in Boolean :=
     Joint_Array_Trig_Pair_Text_Io.Default_Named_Association_Array;
      Named_Association_Element : in Boolean :=
     Joint_Array_Trig_Pair_Text_Io.Default_Named_Association_Element) renames
     Joint_Array_Trig_Pair_Text_Io.Get;
   procedure Get
     (Item                      : out Joint_Array_Trig_Pair_Type;
      Named_Association_Array   : in Boolean :=
     Joint_Array_Trig_Pair_Text_Io.Default_Named_Association_Array;
      Named_Association_Element : in Boolean :=
     Joint_Array_Trig_Pair_Text_Io.Default_Named_Association_Element) renames
     Joint_Array_Trig_Pair_Text_Io.Get;
   procedure Get_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : out Joint_Array_Trig_Pair_Type;
      Named_Association : in Boolean := False) renames
     Joint_Array_Trig_Pair_Text_Io.Get_Item;

   procedure Put
     (File                      : in Ada.Text_IO.File_Type;
      Item                      : in Jacobian_Type;
      Single_Line_Array         : in Boolean := False;
      Named_Association_Array   : in Boolean := False;
      Single_Line_Element       : in Boolean := True;
      Named_Association_Element : in Boolean := False);
   procedure Put
     (Item                      : in Jacobian_Type;
      Single_Line_Array         : in Boolean := False;
      Named_Association_Array   : in Boolean := False;
      Single_Line_Element       : in Boolean := True;
      Named_Association_Element : in Boolean := False);
   procedure Put_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : in Jacobian_Type;
      Single_Line       : in Boolean := False;
      Named_Association : in Boolean := False);

   procedure Get
     (File                      : in Ada.Text_IO.File_Type;
      Item                      : out Jacobian_Type;
      Named_Association_Array   : in Boolean := False;
      Named_Association_Element : in Boolean := False);
   procedure Get
     (Item                      : out Jacobian_Type;
      Named_Association_Array   : in Boolean := False;
      Named_Association_Element : in Boolean := False);
   procedure Get_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : out Jacobian_Type;
      Named_Association : in Boolean := False);

   procedure Put
     (File                      : in Ada.Text_IO.File_Type;
      Item                      : in Inverse_Jacobian_Type;
      Single_Line_Array         : in Boolean := False;
      Named_Association_Array   : in Boolean := False;
      Single_Line_Element       : in Boolean := True;
      Named_Association_Element : in Boolean := False);
   procedure Put
     (Item                      : in Inverse_Jacobian_Type;
      Single_Line_Array         : in Boolean := False;
      Named_Association_Array   : in Boolean := False;
      Single_Line_Element       : in Boolean := True;
      Named_Association_Element : in Boolean := False);
   procedure Put_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : in Inverse_Jacobian_Type;
      Single_Line       : in Boolean := False;
      Named_Association : in Boolean := False);

   procedure Get
     (File                      : in Ada.Text_IO.File_Type;
      Item                      : out Inverse_Jacobian_Type;
      Named_Association_Array   : in Boolean := False;
      Named_Association_Element : in Boolean := False);
   procedure Get
     (Item                      : out Inverse_Jacobian_Type;
      Named_Association_Array   : in Boolean := False;
      Named_Association_Element : in Boolean := False);
   procedure Get_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : out Inverse_Jacobian_Type;
      Named_Association : in Boolean := False);

   procedure Put
     (File                      : in Ada.Text_IO.File_Type;
      Item                      : in Projector_Type;
      Single_Line_Array         : in Boolean := False;
      Named_Association_Array   : in Boolean := False;
      Single_Line_Element       : in Boolean := True;
      Named_Association_Element : in Boolean := False);
   procedure Put
     (Item                      : in Projector_Type;
      Single_Line_Array         : in Boolean := False;
      Named_Association_Array   : in Boolean := False;
      Single_Line_Element       : in Boolean := True;
      Named_Association_Element : in Boolean := False);
   procedure Put_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : in Projector_Type;
      Single_Line       : in Boolean := False;
      Named_Association : in Boolean := False);

   procedure Get
     (File                      : in Ada.Text_IO.File_Type;
      Item                      : out Projector_Type;
      Named_Association_Array   : in Boolean := False;
      Named_Association_Element : in Boolean := False);
   procedure Get
     (Item                      : out Projector_Type;
      Named_Association_Array   : in Boolean := False;
      Named_Association_Element : in Boolean := False);
   procedure Get_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : out Projector_Type;
      Named_Association : in Boolean := False);

   procedure Put
     (File                      : in Ada.Text_IO.File_Type;
      Item                      : in Inertia_Type;
      Single_Line_Array         : in Boolean := False;
      Named_Association_Array   : in Boolean := False;
      Single_Line_Element       : in Boolean := True;
      Named_Association_Element : in Boolean := False);
   procedure Put
     (Item                      : in Inertia_Type;
      Single_Line_Array         : in Boolean := False;
      Named_Association_Array   : in Boolean := False;
      Single_Line_Element       : in Boolean := True;
      Named_Association_Element : in Boolean := False);
   procedure Put_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : in Inertia_Type;
      Single_Line       : in Boolean := False;
      Named_Association : in Boolean := False);

   procedure Get
     (File                      : in Ada.Text_IO.File_Type;
      Item                      : out Inertia_Type;
      Named_Association_Array   : in Boolean := False;
      Named_Association_Element : in Boolean := False);
   procedure Get
     (Item                      : out Inertia_Type;
      Named_Association_Array   : in Boolean := False;
      Named_Association_Element : in Boolean := False);
   procedure Get_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : out Inertia_Type;
      Named_Association : in Boolean := False);

end Sal.Gen_Math.Gen_Manipulator.Gen_Text_Io;
