--  Abstract :
--
--  Text_IO for types in SAL.Gen_Math.Gen_Polynomials
--
--  This file is auto-generated by auto_text_io
--  from SAL.Gen_Math.Gen_Polynomials
--
with Sal.Gen_Array_Text_Io;
with Sal.Gen_Math.Gen_Text_Io;
with Ada.Text_IO;
generic
   with package Math_Text_Io is new Sal.Gen_Math.Gen_Text_Io;
package Sal.Gen_Math.Gen_Polynomials.Gen_Text_Io is

   package Coefficients_Text_Io is new
     Sal.Gen_Array_Text_Io.Unconstrained_Float_1D (
      Element_Type => Real_Type,
      Index_Type => Natural,
      Index_Array_Element_Type => Coefficients_Type,
      Element_Put => Math_Text_Io.Put,
      Element_Get => Math_Text_Io.Get);
   procedure Put
     (File              : in Ada.Text_IO.File_Type;
      Item              : in Coefficients_Type;
      Fore              : in Ada.Text_IO.Field :=
     Coefficients_Text_Io.Default_Fore;
      Aft               : in Ada.Text_IO.Field :=
     Coefficients_Text_Io.Default_Aft;
      Exp               : in Ada.Text_IO.Field :=
     Coefficients_Text_Io.Default_Exp;
      Single_Line       : in Boolean           :=
     Coefficients_Text_Io.Default_Single_Line;
      Named_Association : in Boolean           :=
     Coefficients_Text_Io.Default_Named_Association) renames
     Coefficients_Text_Io.Put;
   procedure Get
     (File              : in Ada.Text_IO.File_Type;
      Item              : out Coefficients_Type;
      Width             : in Ada.Text_IO.Field := 0;
      Named_Association : in Boolean           :=
     Coefficients_Text_Io.Default_Named_Association) renames
     Coefficients_Text_Io.Get;
   procedure Put
     (Item              : in Coefficients_Type;
      Fore              : in Ada.Text_IO.Field :=
     Coefficients_Text_Io.Default_Fore;
      Aft               : in Ada.Text_IO.Field :=
     Coefficients_Text_Io.Default_Aft;
      Exp               : in Ada.Text_IO.Field :=
     Coefficients_Text_Io.Default_Exp;
      Single_Line       : in Boolean           :=
     Coefficients_Text_Io.Default_Single_Line;
      Named_Association : in Boolean           :=
     Coefficients_Text_Io.Default_Named_Association) renames
     Coefficients_Text_Io.Put;
   procedure Get
     (Item              : out Coefficients_Type;
      Width             : in Ada.Text_IO.Field := 0;
      Named_Association : in Boolean           :=
     Coefficients_Text_Io.Default_Named_Association) renames
     Coefficients_Text_Io.Get;
   procedure Put_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : in Coefficients_Type;
      Single_Line       : in Boolean :=
     Coefficients_Text_Io.Default_Single_Line;
      Named_Association : in Boolean :=
     Coefficients_Text_Io.Default_Named_Association) renames
     Coefficients_Text_Io.Put_Item;
   procedure Get_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : out Coefficients_Type;
      Named_Association : in Boolean :=
     Coefficients_Text_Io.Default_Named_Association) renames
     Coefficients_Text_Io.Get_Item;

end Sal.Gen_Math.Gen_Polynomials.Gen_Text_Io;
