--  Abstract :
--
--  Text_IO for types in SAL.Gen_Math.Gen_Den_Hart
--
--  This file is auto-generated by auto_text_io
--  from SAL.Gen_Math.Gen_Den_Hart
--
with Sal.Gen_Math.Gen_Scalar.Gen_Text_Io;
with Sal.Gen_Math.Gen_Text_Io;
with Ada.Text_IO;
generic
   with package Math_Text_Io is new Sal.Gen_Math.Gen_Text_Io;
   with package Math_Scalar_Text_Io is new Parent_Math_Scalar.Gen_Text_Io (
      Math_Text_Io);
package Sal.Gen_Math.Gen_Den_Hart.Gen_Text_Io is
   pragma Elaborate_Body;

   package Joint_Class_Text_Io is new Ada.Text_IO.Enumeration_IO (
      Joint_Class_Type);
   procedure Put
     (File  : in Ada.Text_IO.File_Type;
      Item  : in Joint_Class_Type;
      Width : in Ada.Text_IO.Field    := Joint_Class_Text_Io.Default_Width;
      Set   : in Ada.Text_IO.Type_Set := Joint_Class_Text_Io.Default_Setting) 
renames Joint_Class_Text_Io.Put;
   procedure Get
     (File : in Ada.Text_IO.File_Type;
      Item : out Joint_Class_Type) renames Joint_Class_Text_Io.Get;
   procedure Put
     (Item  : in Joint_Class_Type;
      Width : in Ada.Text_IO.Field    := Joint_Class_Text_Io.Default_Width;
      Set   : in Ada.Text_IO.Type_Set := Joint_Class_Text_Io.Default_Setting) 
renames Joint_Class_Text_Io.Put;
   procedure Get (Item : out Joint_Class_Type) renames Joint_Class_Text_Io.Get;

   procedure Put
     (File                        : in Ada.Text_IO.File_Type;
      Item                        : in Den_Hart_Type;
      Single_Line_Record          : in Boolean := True;
      Named_Association_Record    : in Boolean := False;
      Single_Line_Component       : in Boolean := True;
      Named_Association_Component : in Boolean := False);
   procedure Put
     (Item                        : in Den_Hart_Type;
      Single_Line_Record          : in Boolean := True;
      Named_Association_Record    : in Boolean := False;
      Single_Line_Component       : in Boolean := True;
      Named_Association_Component : in Boolean := False);
   procedure Put_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : in Den_Hart_Type;
      Single_Line       : in Boolean := False;
      Named_Association : in Boolean := False);

   procedure Get
     (File                        : in Ada.Text_IO.File_Type;
      Item                        : out Den_Hart_Type;
      Named_Association_Record    : in Boolean := False;
      Named_Association_Component : in Boolean := False);
   procedure Get
     (Item                        : out Den_Hart_Type;
      Named_Association_Record    : in Boolean := False;
      Named_Association_Component : in Boolean := False);
   procedure Get_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : out Den_Hart_Type;
      Named_Association : in Boolean := False);

end Sal.Gen_Math.Gen_Den_Hart.Gen_Text_Io;
