--  Abstract :
--
--  See spec. This file is auto-generated by auto_text_io
--  from SAL.Gen_Math.Gen_DOF_2
--
with Sal.Text_Io_Utils; use Sal.Text_Io_Utils;
package body Sal.Gen_Math.Gen_Dof_2.Gen_Text_Io is

   use Ada.Text_IO;

   procedure Put
     (File                        : in Ada.Text_IO.File_Type;
      Item                        : in Point_Type;
      Single_Line_Record          : in Boolean := True;
      Named_Association_Record    : in Boolean := False;
      Single_Line_Component       : in Boolean := True;
      Named_Association_Component : in Boolean := False)
   is
      pragma Unreferenced
        (Single_Line_Component,
         Named_Association_Component);
   begin
      Put (File, "(");
      if Named_Association_Record then
         Put (File, "X => ");
         if not Single_Line_Record then
            New_Line (File);
         end if;
      end if;
      Math_Text_Io.Put (File, Item.X);
      Put (File, ',');
      if not Single_Line_Record then
         New_Line (File);
      end if;
      Put (File, ' ');
      if Named_Association_Record then
         Put (File, "Y => ");
         if not Single_Line_Record then
            New_Line (File);
         end if;
      end if;
      Math_Text_Io.Put (File, Item.Y);
      Put (File, ")");
   end Put;

   procedure Put
     (Item                        : in Point_Type;
      Single_Line_Record          : in Boolean := True;
      Named_Association_Record    : in Boolean := False;
      Single_Line_Component       : in Boolean := True;
      Named_Association_Component : in Boolean := False)
   is
   begin
      Put
        (Current_Output,
         Item,
         Single_Line_Record,
         Named_Association_Record,
         Single_Line_Component,
         Named_Association_Component);
   end Put;

   procedure Put_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : in Point_Type;
      Single_Line       : in Boolean := False;
      Named_Association : in Boolean := False)
   is
   begin
      Put
        (File,
         Item,
         Single_Line,
         Named_Association,
         Single_Line,
         Named_Association);
   end Put_Item;

   procedure Get
     (File                        : in Ada.Text_IO.File_Type;
      Item                        : out Point_Type;
      Named_Association_Record    : in Boolean := False;
      Named_Association_Component : in Boolean := False)
   is
      pragma Unreferenced (Named_Association_Component);
      Temp_Item : Point_Type renames Item;
   begin
      Check (File, "(");
      if Named_Association_Record then
         Check (File, "X => ");
      end if;
      Math_Text_Io.Get (File, Temp_Item.X);
      Check (File, ",");
      Skip_Whitespace (File);
      if Named_Association_Record then
         Check (File, "Y => ");
      end if;
      Math_Text_Io.Get (File, Temp_Item.Y);
      Check (File, ")");
   end Get;

   procedure Get
     (Item                        : out Point_Type;
      Named_Association_Record    : in Boolean := False;
      Named_Association_Component : in Boolean := False)
   is
   begin
      Get
        (Current_Input,
         Item,
         Named_Association_Record,
         Named_Association_Component);
   end Get;

   procedure Get_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : out Point_Type;
      Named_Association : in Boolean := False)
   is
   begin
      Get (File, Item, Named_Association, Named_Association);
   end Get_Item;

   procedure Put
     (File                        : in Ada.Text_IO.File_Type;
      Item                        : in Rectangle_Type;
      Single_Line_Record          : in Boolean := True;
      Named_Association_Record    : in Boolean := False;
      Single_Line_Component       : in Boolean := True;
      Named_Association_Component : in Boolean := False)
   is
   begin
      Put (File, "(");
      if Named_Association_Record then
         Put (File, "Left_Bottom => ");
         if not Single_Line_Record then
            New_Line (File);
         end if;
      end if;
      Put_Item
        (File,
         Item.Left_Bottom,
         Single_Line       => Single_Line_Component,
         Named_Association => Named_Association_Component);
      Put (File, ',');
      if not Single_Line_Record then
         New_Line (File);
      end if;
      Put (File, ' ');
      if Named_Association_Record then
         Put (File, "Right_Top => ");
         if not Single_Line_Record then
            New_Line (File);
         end if;
      end if;
      Put_Item
        (File,
         Item.Right_Top,
         Single_Line       => Single_Line_Component,
         Named_Association => Named_Association_Component);
      Put (File, ")");
   end Put;

   procedure Put
     (Item                        : in Rectangle_Type;
      Single_Line_Record          : in Boolean := True;
      Named_Association_Record    : in Boolean := False;
      Single_Line_Component       : in Boolean := True;
      Named_Association_Component : in Boolean := False)
   is
   begin
      Put
        (Current_Output,
         Item,
         Single_Line_Record,
         Named_Association_Record,
         Single_Line_Component,
         Named_Association_Component);
   end Put;

   procedure Put_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : in Rectangle_Type;
      Single_Line       : in Boolean := False;
      Named_Association : in Boolean := False)
   is
   begin
      Put
        (File,
         Item,
         Single_Line,
         Named_Association,
         Single_Line,
         Named_Association);
   end Put_Item;

   procedure Get
     (File                        : in Ada.Text_IO.File_Type;
      Item                        : out Rectangle_Type;
      Named_Association_Record    : in Boolean := False;
      Named_Association_Component : in Boolean := False)
   is
      Temp_Item : Rectangle_Type renames Item;
   begin
      Check (File, "(");
      if Named_Association_Record then
         Check (File, "Left_Bottom => ");
      end if;
      Get_Item
        (File,
         Temp_Item.Left_Bottom,
         Named_Association => Named_Association_Component);
      Check (File, ",");
      Skip_Whitespace (File);
      if Named_Association_Record then
         Check (File, "Right_Top => ");
      end if;
      Get_Item
        (File,
         Temp_Item.Right_Top,
         Named_Association => Named_Association_Component);
      Check (File, ")");
   end Get;

   procedure Get
     (Item                        : out Rectangle_Type;
      Named_Association_Record    : in Boolean := False;
      Named_Association_Component : in Boolean := False)
   is
   begin
      Get
        (Current_Input,
         Item,
         Named_Association_Record,
         Named_Association_Component);
   end Get;

   procedure Get_Item
     (File              : in Ada.Text_IO.File_Type;
      Item              : out Rectangle_Type;
      Named_Association : in Boolean := False)
   is
   begin
      Get (File, Item, Named_Association, Named_Association);
   end Get_Item;

end Sal.Gen_Math.Gen_Dof_2.Gen_Text_Io;
