--  Abstract :
--
--  Text_IO for types in SAL.Gen_Math
--
--  This file is auto-generated by auto_text_io
--  from SAL.Gen_Math
--
with Ada.Text_IO;
generic
package Sal.Gen_Math.Gen_Text_Io is

   package Num_Text_Io is new Ada.Text_IO.Float_IO (Num_Type);
   procedure Put
     (File : in Ada.Text_IO.File_Type;
      Item : in Num_Type;
      Fore : in Ada.Text_IO.Field := Num_Text_Io.Default_Fore;
      Aft  : in Ada.Text_IO.Field := Num_Text_Io.Default_Aft;
      Exp  : in Ada.Text_IO.Field := Num_Text_Io.Default_Exp) renames
     Num_Text_Io.Put;
   procedure Get
     (File  : in Ada.Text_IO.File_Type;
      Item  : out Num_Type;
      Width : in Ada.Text_IO.Field := 0) renames Num_Text_Io.Get;
   procedure Put
     (Item : in Num_Type;
      Fore : in Ada.Text_IO.Field := Num_Text_Io.Default_Fore;
      Aft  : in Ada.Text_IO.Field := Num_Text_Io.Default_Aft;
      Exp  : in Ada.Text_IO.Field := Num_Text_Io.Default_Exp) renames
     Num_Text_Io.Put;
   procedure Get (Item : out Num_Type; Width : in Ada.Text_IO.Field := 0) 
renames Num_Text_Io.Get;

end Sal.Gen_Math.Gen_Text_Io;
